//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameJam_Planner
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoxGenel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BoxGenel()
        {
            this.NoteBox = new HashSet<NoteBox>();
            this.PictureBoxTable = new HashSet<PictureBoxTable>();
            this.ToDoBox = new HashSet<ToDoBox>();
        }
    
        public int BoxID { get; set; }
        public string BoxTitle { get; set; }
        public string BoxLocation { get; set; }
        public string BoxSize { get; set; }
        public string BoxBackColor { get; set; }
        public Nullable<bool> BoxIsLocked { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NoteBox> NoteBox { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PictureBoxTable> PictureBoxTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToDoBox> ToDoBox { get; set; }
    }
}
