//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameJam_Planner
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PlannerEntities : DbContext
    {
        public PlannerEntities()
            : base("name=PlannerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BoxGenel> BoxGenel { get; set; }
        public virtual DbSet<NoteBox> NoteBox { get; set; }
        public virtual DbSet<PictureBoxTable> PictureBoxTable { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<ToDoBox> ToDoBox { get; set; }
        public virtual DbSet<ToDoItems> ToDoItems { get; set; }
    }
}
