//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameJam_Planner
{
    using System;
    using System.Collections.Generic;
    
    public partial class NoteBox
    {
        public int NoteBoxID { get; set; }
        public string NoteBoxText { get; set; }
        public int BoxID { get; set; }
    
        public virtual BoxGenel BoxGenel { get; set; }
    }
}
