//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameJam_Planner
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToDoItems
    {
        public int ToDoItemID { get; set; }
        public string ToDoItemName { get; set; }
        public Nullable<bool> ToDoItemChecked { get; set; }
        public Nullable<int> ToDoBoxID { get; set; }
    
        public virtual ToDoBox ToDoBox { get; set; }
    }
}
