//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameJam_Planner
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToDoBox
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ToDoBox()
        {
            this.ToDoItems = new HashSet<ToDoItems>();
        }
    
        public int ToDoBoxID { get; set; }
        public Nullable<int> BoxID { get; set; }
    
        public virtual BoxGenel BoxGenel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToDoItems> ToDoItems { get; set; }
    }
}
